package views;

import theotherhattrick.Game;
import theotherhattrick.Player;
import theotherhattrick.controllers.DiscardWindowController;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class DiscardWindow extends JFrame {
    private JPanel panel1;
    private JButton card0;
    private JButton card1;
    private JButton card2;

    private Game game;

    public DiscardWindow() {
        game = Game.getInstance();

        this.setTitle("Discard window");
        this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        this.setSize(600, 200);
        this.setContentPane(this.getPanel());
        this.setVisible(true);

        showCards();

        new DiscardWindowController(this);
    }

    public void showCards() {
        card0.setText(game.getCurrentPlayer().getHand().get(0).getName());
        card1.setText(game.getCurrentPlayer().getHand().get(1).getName());
        card2.setText(game.getCurrentPlayer().getHand().get(2).getName());

        Player currentPlayer = Game.getInstance().getCurrentPlayer();
        card0.setText(currentPlayer.getHand().get(0).getName());
        MainWindow.putImageProp(card0);
        card1.setText(currentPlayer.getHand().get(1).getName());
        MainWindow.putImageProp(card1);
        card2.setText(currentPlayer.getHand().get(2).getName());
        MainWindow.putImageProp(card2);
    }

    public JButton getCard0() {
        return this.card0;
    }

    public JButton getCard1() {
        return this.card1;
    }

    public JButton getCard2() {
        return this.card2;
    }

    public JPanel getPanel() {
        return this.panel1;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        final JLabel label1 = new JLabel();
        label1.setText("Trick réussi !");
        panel1.add(label1);
        card0 = new JButton();
        card0.setText("Button");
        panel1.add(card0);
        card1 = new JButton();
        card1.setText("Button");
        panel1.add(card1);
        card2 = new JButton();
        card2.setText("Button");
        panel1.add(card2);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}