package views;

import theotherhattrick.Player;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class DiscardWindow {
    private JFrame frame;
    private JPanel panel1;
    private JButton card0;
    private JButton card1;
    private JButton card2;
    private MainWindow mainWindow;

    public DiscardWindow(MainWindow mainWindow) {
        this.mainWindow = mainWindow;

        card0.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mainWindow.putSeventhProp(0);
                frame.dispose();
            }
        });
        card1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mainWindow.putSeventhProp(1);
                frame.dispose();
            }
        });
        card2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mainWindow.putSeventhProp(2);
                frame.dispose();
            }
        });
    }

    public void showCards(Player currentPlayer) {
        card0.setText(currentPlayer.getHand().get(0).getName());
        card1.setText(currentPlayer.getHand().get(1).getName());
        card2.setText(currentPlayer.getHand().get(2).getName());
    }

    public void addFrame(JFrame frame) {
        this.frame = frame;
    }

    public JPanel getPanel() {
        return this.panel1;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        final JLabel label1 = new JLabel();
        label1.setText("Trick réussi !");
        panel1.add(label1);
        card0 = new JButton();
        card0.setText("Button");
        panel1.add(card0);
        card1 = new JButton();
        card1.setText("Button");
        panel1.add(card1);
        card2 = new JButton();
        card2.setText("Button");
        panel1.add(card2);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
