package views;

import theotherhattrick.Player;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

public class PickWindow {
    private JFrame frame;
    private JPanel panel1;
    private JButton card00;
    private JButton card01;
    private JButton card10;
    private JButton card11;
    private JLabel label0;
    private JLabel label1;
    private ArrayList<JButton> buttons;
    private List<Player> players;
    private MainWindow mainWindow;

    public PickWindow(MainWindow mainWindow) {
        this.mainWindow = mainWindow;

        card00.addActionListener(new ActionListener() { // ajouter le contrôleur
            @Override
            public void actionPerformed(ActionEvent e) {
                mainWindow.exchange(players.get(0), 0);
                frame.dispose();
            }
        });
        card01.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mainWindow.exchange(players.get(0), 1);
                frame.dispose();
            }
        });
        card10.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mainWindow.exchange(players.get(1), 0);
                frame.dispose();
            }
        });
        card11.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mainWindow.exchange(players.get(1), 1);
                frame.dispose();
            }
        });
    }

    public void showCards(List<Player> players, Player currentPlayer) {
        this.buttons = new ArrayList<JButton>();
        this.players = new ArrayList<Player>();

        this.buttons.add(card00);
        this.buttons.add(card01);
        this.buttons.add(card10);
        this.buttons.add(card11);

        int i = 0;
        for (Player player : players) {
            if (player != currentPlayer) {
                this.players.add(player);
                buttons.get(i).setText(player.getHand().get(0).toString());
                i++;
                buttons.get(i).setText(player.getHand().get(1).toString());
                i++;
            }
        }

        label0.setText(this.players.get(0).getName());
        label1.setText(this.players.get(1).getName());
    }

    public void addFrame(JFrame frame) {
        this.frame = frame;
    }

    public JPanel getPanel() {
        return this.panel1;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel2.setPreferredSize(new Dimension(300, 0));
        panel2.setRequestFocusEnabled(true);
        panel1.add(panel2, BorderLayout.WEST);
        label0 = new JLabel();
        label0.setText("Label");
        panel2.add(label0);
        card00 = new JButton();
        card00.setText("Button");
        panel2.add(card00);
        card01 = new JButton();
        card01.setText("Button");
        panel2.add(card01);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel3.setPreferredSize(new Dimension(300, 0));
        panel1.add(panel3, BorderLayout.EAST);
        label1 = new JLabel();
        label1.setText("Label");
        panel3.add(label1);
        card10 = new JButton();
        card10.setText("Button");
        panel3.add(card10);
        card11 = new JButton();
        card11.setText("Button");
        panel3.add(card11);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}