package views;

import javax.swing.*;
import java.awt.*;

public class TurnCardWindow extends JFrame {
    private JButton card0;
    private JPanel panel1;
    private JButton card1;

    public TurnCardWindow() {
        this.setTitle("Turn card window");
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        this.setSize(400, 250);
        this.setContentPane(this.getPanel());
        this.setVisible(true);
    }

    public JPanel getPanel() {
        return this.panel1;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        card0 = new JButton();
        card0.setText("Button");
        panel1.add(card0);
        card1 = new JButton();
        card1.setText("Button");
        panel1.add(card1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
